import { TopUser } from './topUser';

export interface Breakdown {
  proAccuracy: number;
  moderateAccuracy: number;
  antiAccuracy: number;
  proCount: number;
  moderateCount: number;
  antiCount: number;
  allUsersAccuracy: number;
  proApbtCount: number;
  proApbtAccuracy: number;
  proMultiCount: number;
  proMultiAccuracy: number;
  moderateApbtCount: number;
  moderateApbtAccuracy: number;
  moderateMultiCount: number;
  moderateMultiAccuracy: number;
  antiApbtCount: number;
  antiApbtAccuracy: number;
  antiMultiCount: number;
  antiMultiAccuracy: number;
  topUsers: TopUser[];
  proPercentage25: number;
  proPercentage50: number;
  proPercentage75: number;
  proPercentageGreaterThan75: number;
  moderatePercentage25: number;
  moderatePercentage50: number;
  moderatePercentage75: number;
  moderatePercentageGreaterThan75: number;
  antiPercentage25: number;
  antiPercentage50: number;
  antiPercentage75: number;
  antiPercentageGreaterThan75: number;
  antiApbt: number;
  antiAst: number;
  antiSbt: number;
  antiAb: number;
  proApbt: number;
  proAst: number;
  proSbt: number;
  proAb: number;
  moderateApbt: number;
  moderateAst: number;
  moderateSbt: number;
  moderateAb: number;
}